
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Remplacez ces valeurs par les informations de votre nouveau projet Supabase
const SUPABASE_URL = "https://votre_nouveau_project_id.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "votre_nouvelle_cle_anon";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
